// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

/**
 * 品牌相关的常量配置
 *
 * 这个文件用于替换 webapp/channels/src/utils/constants.tsx 中的链接常量
 * 使用前端品牌配置覆盖原有的链接
 */

import { BRAND_CONFIG } from './brand_config';

// 重新导出品牌链接配置
export const AboutLinks = {
  TERMS_OF_SERVICE: BRAND_CONFIG.LINKS.TERMS_OF_SERVICE,
  PRIVACY_POLICY: BRAND_CONFIG.LINKS.PRIVACY_POLICY,
};

export const CloudLinks = {
  BILLING_DOCS: BRAND_CONFIG.LINKS.BILLING_DOCS,
  PRICING: BRAND_CONFIG.LINKS.PRICING,
  DEPLOYMENT_OPTIONS: BRAND_CONFIG.LINKS.DEPLOYMENT_OPTIONS,
  DOWNLOAD_UPDATE: BRAND_CONFIG.LINKS.DEPLOYMENT_OPTIONS,
  CLOUD_SIGNUP_PAGE: BRAND_CONFIG.LINKS.CLOUD_SIGNUP,
  SELF_HOSTED_PRICING: BRAND_CONFIG.LINKS.PRICING,
};

export const HostedCustomerLinks = {
  BILLING_DOCS: BRAND_CONFIG.LINKS.BILLING_DOCS,
  SELF_HOSTED_BILLING: BRAND_CONFIG.LINKS.BILLING_DOCS,
  TERMS_AND_CONDITIONS: BRAND_CONFIG.LINKS.TERMS_OF_SERVICE,
  SECURITY_UPDATES: BRAND_CONFIG.LINKS.MAIN,
  DOWNLOAD: BRAND_CONFIG.LINKS.MAIN,
  PRIVACY: BRAND_CONFIG.LINKS.PRIVACY_POLICY,
};

export const DocLinks = {
  ABOUT_TEAMS: BRAND_CONFIG.LINKS.DOCS,
  ADVANCED_LOGGING: BRAND_CONFIG.LINKS.DOCS,
  CONFIGURE_DOCUMENT_CONTENT_SEARCH: BRAND_CONFIG.LINKS.DOCS,
  CONFIGURE_AD_LDAP_QUERY_TIMEOUT: BRAND_CONFIG.LINKS.DOCS,
  CONFIGURE_OVERRIDE_SAML_BIND_DATA_WITH_LDAP: BRAND_CONFIG.LINKS.DOCS,
  COMPLIANCE_EXPORT: BRAND_CONFIG.LINKS.DOCS,
  COMPLIANCE_MONITORING: BRAND_CONFIG.LINKS.DOCS,
  DATA_RETENTION_POLICY: BRAND_CONFIG.LINKS.DOCS,
  DEFAULT_LDAP_GROUP_SYNC: BRAND_CONFIG.LINKS.DOCS,
  DESKTOP_MANAGED_RESOURCES: BRAND_CONFIG.LINKS.DOCS,
  ELASTICSEARCH: BRAND_CONFIG.LINKS.DOCS,
  ENABLE_HARDENED_MODE: BRAND_CONFIG.LINKS.DOCS,
  FORMAT_MESSAGES: BRAND_CONFIG.LINKS.DOCS,
  FILE_STORAGE: BRAND_CONFIG.LINKS.DOCS,
  GUEST_ACCOUNTS: BRAND_CONFIG.LINKS.DOCS,
  HIGH_AVAILABILITY_CLUSTER: BRAND_CONFIG.LINKS.DOCS,
  IN_PRODUCT_NOTICES: BRAND_CONFIG.LINKS.DOCS,
  MULTI_FACTOR_AUTH: BRAND_CONFIG.LINKS.DOCS,
  ONBOARD_ADVANCED_PERMISSIONS: BRAND_CONFIG.LINKS.DOCS,
  ONBOARD_LDAP: BRAND_CONFIG.LINKS.DOCS,
  SELF_HOSTED_BILLING: BRAND_CONFIG.LINKS.BILLING_DOCS,
  SESSION_LENGTHS: BRAND_CONFIG.LINKS.DOCS,
  SETUP_IMAGE_PROXY: BRAND_CONFIG.LINKS.DOCS,
  SETUP_LDAP: BRAND_CONFIG.LINKS.DOCS,
  SETUP_PERFORMANCE_MONITORING: BRAND_CONFIG.LINKS.DOCS,
  SETUP_PUSH_NOTIFICATIONS: BRAND_CONFIG.LINKS.DOCS,
  SETUP_SAML: BRAND_CONFIG.LINKS.DOCS,
  SHARE_LINKS_TO_MESSAGES: BRAND_CONFIG.LINKS.DOCS,
  SITE_URL: BRAND_CONFIG.LINKS.DOCS,
  SSL_CERTIFICATE: BRAND_CONFIG.LINKS.DOCS,
  TRUE_UP_REVIEW: BRAND_CONFIG.LINKS.DOCS,
  TRUSTED_CONNECTION: BRAND_CONFIG.LINKS.DOCS,
  UPGRADE_SERVER: BRAND_CONFIG.LINKS.DOCS,
};

export const DeveloperLinks = {
  CUSTOM_SLASH_COMMANDS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  ENABLE_OAUTH2: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  INCOMING_WEBHOOKS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  OUTGOING_WEBHOOKS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  INTERACTIVE_MESSAGES: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  INTERACTIVE_DIALOGS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  PERSONAL_ACCESS_TOKENS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  PLUGIN_SIGNING: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  PLUGINS: BRAND_CONFIG.LINKS.PLUGINS,
  SETUP_CUSTOM_SLASH_COMMANDS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  SETUP_INCOMING_WEBHOOKS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  SETUP_OAUTH2: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
  SETUP_OUTGOING_WEBHOOKS: BRAND_CONFIG.LINKS.DEVELOPER_DOCS,
};

export const LicenseLinks = {
  CONTACT_SALES: BRAND_CONFIG.LINKS.CONTACT_SALES,
  ENTRY_LIMITS_INFO: BRAND_CONFIG.LINKS.DOCS,
  TRIAL_INFO_LINK: BRAND_CONFIG.LINKS.TRIAL_INFO,
  EMBARGOED_COUNTRIES: BRAND_CONFIG.LINKS.DOCS,
  SOFTWARE_SERVICES_LICENSE_AGREEMENT: BRAND_CONFIG.LINKS.TERMS_OF_SERVICE,
  SOFTWARE_SERVICES_LICENSE_AGREEMENT_TEXT: 'Software Services and License Agreement',
  UNSUPPORTED: BRAND_CONFIG.LINKS.PRICING,
  UNSUPPORTED_UPGRADE_LINK: BRAND_CONFIG.LINKS.DOCS,
};

export const MattermostLink = BRAND_CONFIG.LINKS.MAIN;
